### ISSUE TITLE
[conda] Python 3.7.4 package is broken

### ISSUE THREAD

**Issue by jhunkeler** [astroconda/astroconda-contrib#544]
The failure below is specific to conda's Python 3.7.4 package. This issue does not appear when using a Python interpreter just-compiled from source.

## Temporary solution(s):

```bash 
$ conda install python=3.7.3
# and
$ conda build --python=3.7.3 [...]
```

## Sample:
```
building 'calcos.ccos' extension
creating build/temp.linux-x86_64-3.7
creating build/temp.linux-x86_64-3.7/src
gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DNUMPY=1 -I/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib/python3.7/site-packages/numpy/core/include -I/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/include/python3.7m -c src/ccos.c -o build/temp.linux-x86_64-3.7/src/ccos.o
In file included from /srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1824,
                 from /srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from src/ccos.c:119:
/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION"
src/ccos.c: In function ‘ccos_pha_check’:
src/ccos.c:2406: warning: ‘nlow’ may be used uninitialized in this function
src/ccos.c:2406: warning: ‘nhigh’ may be used uninitialized in this function
gcc -pthread -shared -L/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib -Wl,-rpath=/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/src/ccos.o -o build/lib.linux-x86_64-3.7/calcos/ccos.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so
/usr/bin/ld: this linker was not configured to use sysroots
collect2: ld returned 1 exit status
/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/_h_env_placeh/lib/python3.7/site-packages/setuptools/dist.py:45: DistDeprecationWarning: Do not call this function
  warnings.warn("Do not call this function", DistDeprecationWarning)
error: command 'gcc' failed with exit status 1
Traceback (most recent call last):
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 424, in main
    execute(sys.argv[1:])
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 415, in execute
    verify=args.verify)
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/lib/python3.7/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 2206, in build_tree
    notest=notest,
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/lib/python3.7/site-packages/conda_build/build.py", line 1446, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 310, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/lib/python3.7/site-packages/conda_build/utils.py", line 290, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/srv/jenkins/workspace/AstroConda/public_RHEL-6_py3.7_np1.16/_dispatch/miniconda/conda-bld/calcos_1565724069928/work/conda_build.sh']' returned non-zero exit status 1.
```

**Comment by jhunkeler** [comment]
Ref: https://github.com/ContinuumIO/anaconda-issues/issues/11195

**Comment by jhunkeler** [comment]
Fixed upstream.
