### ISSUE TITLE
Read time out downloading IRAF

### ISSUE THREAD

**Issue by crawfordsm** [astroconda/astroconda-contrib#79]
I'm trying to install IRAF from astroconda and there keeps being timeout issues.   I can install the rest of the conda packages as well as packages from astroconda, but it seems like the IRAF package is taking an extremely long time to download and then after 40 minutes it is timing out.

**Comment by crawfordsm** [comment]
Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/crawford/anaconda  (writable)
    default environment : /Users/crawford/anaconda/envs/pysalt
       envs directories : /Users/crawford/anaconda/envs
          package cache : /Users/crawford/anaconda/pkgs
           channel URLs : http://ssb.stsci.edu/astroconda/osx-64/
                          http://ssb.stsci.edu/astroconda/noarch/
                          https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/crawford/.condarc
           offline mode : False



`$ /Users/crawford/anaconda/envs/pysalt/bin/conda install iraf pyraf stsci`




    Traceback (most recent call last):
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
        yield
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
        data = self._fp.read(amt)
      File "/Users/crawford/anaconda/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/Users/crawford/anaconda/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/Users/crawford/anaconda/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/requests/models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
        flush_decoder = True
      File "/Users/crawford/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='ssb.stsci.edu', port=80): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/requests/models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPConnectionPool(host='ssb.stsci.edu', port=80): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/Users/crawford/anaconda/pkgs/iraf-2.16.1-1.tar.bz2.part' for writing (HTTPConnectionPool(host='ssb.stsci.edu', port=80): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/Users/crawford/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/Users/crawford/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/Users/crawford/anaconda/pkgs/iraf-2.16.1-1.tar.bz2.part' for writing (HTTPConnectionPool(host='ssb.stsci.edu', port=80): Read timed out.).

**Comment by pllim** [comment]
@jhunkeler , was the server that hosts these IRAF packages moved to Rotunda? I have connection problem with my other machine due to the move and I wonder if this is the same kind of issue.
